
exports.FAQView = require('./faq.vue')
exports.CategoriesView = require('./categories.vue')
exports.LoadingView = require('./loading.vue')
exports.HomeView = require('./home.vue')
exports.LoginView = require('./login.vue')
exports.ProjectView = require('./project.vue')
exports.ProfileView = require('./profile.vue')
exports.NotFoundView = require('./not-found.vue')
exports.ErrorView = require('./error.vue')
